// Using a Record type for a key-value map where keys are strings (bank names) and values are strings (logo URLs).
export const BANK_LOGOS: Record<string, string> = {
  'AXA': 'https://cdn.worldvectorlogo.com/logos/axa-banque.svg',
  'BANQUE BARCLAYS': 'https://i.pinimg.com/1200x/1c/bf/05/1cbf058a456d865689e88e5a7218a1db.jpg',
  'BANQUE CIC': 'https://upload.wikimedia.org/wikipedia/fr/archive/a/a7/20191211005939%21Cic_logo.svg',
  'BANQUE DE SAVOIE': 'https://pickthebank.eu/_next/image/?url=http%3A%2F%2Fbalancer%2Fstorage%2Fpublic%2Fbanks-logo%2Fbank854FR.jpg&w=1200&q=75',
  'BANQUE HERVET': 'https://cdn.worldvectorlogo.com/logos/banque-hervet.svg',
  'BANQUE POPULAIRE': 'https://cdn.worldvectorlogo.com/logos/banque-populaire.svg',
  'BNP PARIBAS': 'https://cdn.worldvectorlogo.com/logos/bnp-paribas-1.svg',
  'BOURSORAMA': 'https://images.seeklogo.com/logo-png/27/1/boursorama-banque-logo-png_seeklogo-270592.png',
  'CAISSE D\'ÉPARGNE': 'https://cdn.worldvectorlogo.com/logos/caisse-d-epargne-2.svg',
  'CNP ASSURANCES': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_CNP_Assurances.svg/500px-Logo_CNP_Assurances.svg.png',
  'CREDIT AGRICOLE': 'https://cdn.worldvectorlogo.com/logos/credit-agricole.svg',
  'CRÉDIT COOPÉRATIF': 'https://upload.wikimedia.org/wikipedia/fr/thumb/2/2e/Logo_Cr%C3%A9dit_Coop%C3%A9ratif.svg/1200px-Logo_Cr%C3%A9dit_Coop%C3%A9ratif.svg.png',
  'CRÉDIT DU NORD': 'https://cdn.worldvectorlogo.com/logos/credit-du-nord.svg',
  'CRÉDIT LYONNAIS': 'https://upload.wikimedia.org/wikipedia/fr/thumb/0/0b/Lcl_logo.svg/2540px-Lcl_logo.svg.png',
  'CREDIT MARITIME': 'https://upload.wikimedia.org/wikipedia/fr/3/39/Credit_maritime_logo.png',
  'CRÉDIT MUNICIPAL': 'https://cdn.worldvectorlogo.com/logos/credit-municipal.svg',
  'CREDIT MUTUEL ARKEA': 'https://thebanks.eu/img/logos/Arkea.png',
  'CREDIT MUTUEL DE BRETAGNE': 'https://upload.wikimedia.org/wikipedia/fr/thumb/7/71/Logo_Cr%C3%A9dit_Mutuel_de_Bretagne_CMB.svg/2560px-Logo_Cr%C3%A9dit_Mutuel_de_Bretagne_CMB.svg.png',
  'CREDIT MUTUEL': 'https://cdn.worldvectorlogo.com/logos/credit-mutuel.svg',
  'GROUPAMA': 'https://cdn.worldvectorlogo.com/logos/groupama-2016.svg',
  'HNBC': 'https://cdn.worldvectorlogo.com/logos/hsbc-3.svg',
  'MONABANQ': 'https://cdn.worldvectorlogo.com/logos/logo-monabanq-gris.svg',
  'NICKEL': 'https://upload.wikimedia.org/wikipedia/fr/thumb/2/2b/Nickel-logo.svg/640px-Nickel-logo.svg.png',
  'QONTO': 'https://cdn.worldvectorlogo.com/logos/qonto-2016.svg',
  'REVOLUT': 'https://cdn.worldvectorlogo.com/logos/revolut-1.svg',
  'SOCIÉTÉ GÉNÉRALE': 'https://cdn.worldvectorlogo.com/logos/societe-generale.svg',
  'SOCIETE MARSEILLAISE DE CREDIT': 'https://aides-territoires-prod-2.s3.fr-par.scw.cloud/aides-territoires-prod/backers/societe-marseillaise-de-credit_logo.png',
  'TARNEAUD': 'https://www.trouver-sa-banque.com/sites/trouver-sa-banque.com/files/2022-12/tarneaud.png',
};
